---
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace

---
apiVersion: v1
kind: Namespace
metadata:
  name: helloworld

---
apiVersion: v1
kind: Namespace
metadata:
  name: foo

---
apiVersion: v1
kind: Namespace
metadata:
  name: bar