---
apiVersion: v1
kind: Namespace
metadata:
  name: nexus

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: cicd
  name: nexus-server
  namespace: nexus
spec:
  replicas: 1
  selector:
    matchLabels:
      component: cicd
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: nexus-server-pod
      labels:
        component: cicd
    spec:
      containers:
        - image: sonatype/nexus3:latest
          name: nexus-container
          ports:
            - containerPort: 8081
              name: nexus-port
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: nexus-service
  namespace: nexus
  labels:
    component: cicd
spec:
  ports:
    - name: nexus-svc-port
      protocol: TCP
      port: 8081
      targetPort: nexus-port
  selector:
    component: cicd
  type: NodePort